### ISSUE TITLE
Install pretalx-media-ccc-de Plugin in docker

### ISSUE THREAD

**Issue by MasterEmit** [pretalx/pretalx-media-ccc-de#2]
Is there any documentation, how the plugin can be installed in a docker container build from pretalx-docker?

Greetz
Alex

**Comment by rixx** [comment]
Sorry, the Docker install isn't one that is officially supported, and we don't have guidance on how to make plugins work. As the pretalx-docker repository is community maintained, you could look there if there is any documentation or past issues, or otherwise open an issue there!
